services:
  caddy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - fleet_api

networks:
  fleet_api:
    external: true
    name: apl-fleet-vps_default
